name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build the production version of the site
      run: npm run build
      env:
        CI: true

    - name: Copy metatag image to output
      run: mkdir -p ./dist/img/ && cp ./src/img/metatag.png ./dist/img/

    # Not necessarily since 2025
    # - name: Deploy through SFTP
    #   uses: SamKirkland/FTP-Deploy-Action@3.0.0
    #   with:
    #     ftp-server: sftp://asmi.ro/smarthack
    #     ftp-username: ${{ secrets.FTP_USERNAME }}
    #     ftp-password: ${{ secrets.FTP_PASSWORD }}
    #     git-ftp-args: --insecure
    #     local-dir: dist/
